from .core import BaseComponent


class BaseComponents:
    class Head(BaseComponent): ...

    class Script(BaseComponent): ...

    class Link(BaseComponent): ...

    class Body(BaseComponent): ...

    class HTML(BaseComponent): ...

    class A(BaseComponent): ...

    class P(BaseComponent): ...

    class Span(BaseComponent): ...

    class Label(BaseComponent): ...

    class Button(BaseComponent): ...

    class Div(BaseComponent): ...

    class Li(BaseComponent): ...

    class Ul(BaseComponent): ...

    class Input(BaseComponent): ...

    class Legend(BaseComponent): ...

    class Form(BaseComponent): ...

    class Symbol(BaseComponent):
        tag_name = "span"

        @property
        def symbol(self) -> str:
            attr = self.attrs.get("symbol", None)
            if not attr:
                raise ValueError("Symbol requires symbol attribute")
            return str(attr)

        def _build(self):
            self.css("material-symbols-outlined")
            self.append(self.symbol)
